# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CEROUNO CURRICULUM
email: contacto@cerouno.io
description: >
  Este el sitio del curriculum de CEROUNO, primer programa de
  aprendizaje acelerado para aprender a programar en México en tres meses.
  No necesitas experiencia previa.
baseurl: ''
permalink: /:title
url: 'http://curriculum.cerouno.io'
twitter_username: cerounoio
github_username:  cerounoio

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'LICENSE',
  'CNAME',
  'lessons/wad/m1/archive',
  'lessons/wad/m2/archive',
  'lessons/wad/m3/archive',
]

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'

assets:
  root_url: '/assets'

images:
  root_url: '/assets/images'
