title: CEROUNO CURRICULUM
email: contacto@cerouno.io
description: >
  Este el sitio del curriculum de CEROUNO, primer programa de
  aprendizaje acelerado para aprender a programar en México en tres meses.
  No necesitas experiencia previa.
baseurl: ''
permalink: /:title
url: https://curriculum.cerouno.io
twitter_username: cerounoio
github_username:  cerounoio

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'LICENSE',
  'CNAME',
  'lessons/wad/m1/archive',
  'lessons/wad/m2/archive',
  'lessons/wad/m3/archive',
  'config.ru',
  'vendor'
]

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'

assets:
  root_url: '/assets'

images:
  root_url: '/assets/images'

fonts:
  root_url: '/assets/fonts'

sass:
  sass_dir: '/assets/css'

github:
  source:
    branch: master
